version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yinebeb
      POSTGRES_PASSWORD: yinebeb
      POSTGRES_DB: price_est
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8084:8084"
    environment:
      - PORT=8082
      - DATABASE_URL=postgres://yinebeb:yinebeb@db:5432/price_est?sslmode=disable
    depends_on:
      - db

volumes:
  db-data:
