version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yinebeb
      POSTGRES_PASSWORD: yinebeb
      POSTGRES_DB: price_est
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    command: ["/app/wait-for-it.sh", "db:5432", "--","go","run","./cmd/main.go"]
    ports:
      - "8082:8082"
    environment:
      CONFIG_NAME: config
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  db-data:
