version: "2"
sql:
  - schema: "../internal/constants/query/schemas/"
    queries: "../internal/constants/query/queries/"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "../internal/constants/model/db"
        sql_package: "pgx/v4"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: true
        emit_exact_table_names: false
        emit_empty_slices: true
        overrides:
          - db_type: "pg_catalog.numeric"
            go_type: "github.com/shopspring/decimal.Decimal"
            nullable: true
