// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Location struct {
	ID        uuid.UUID `json:"id"`
	Country   string    `json:"country"`
	Region    string    `json:"region"`
	Zone      string    `json:"zone"`
	City      string    `json:"city"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PriceEstimation struct {
	ID          uuid.UUID       `json:"id"`
	ProductName string          `json:"product_name"`
	UserID      uuid.UUID       `json:"user_id"`
	Price       decimal.Decimal `json:"price"`
	LocationID  uuid.UUID       `json:"location_id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
